#!/usr/bin/env node

var path = require('path');

process.env.NODE_PATH = [
    path.resolve(__dirname, '../src')
].join(':');

require(path.resolve(process.cwd(), './node_modules/node-nerve/utils/runner'));